# Generated by Django 3.0 on 2021-08-28 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceOfStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField(null=True)),
                ('order', models.IntegerField(default=0)),
                ('questionOfStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionOfStudent')),
            ],
        ),
    ]
