# Generated by Django 3.0 on 2021-09-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_choiceofstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionofstudent',
            name='question_content',
            field=models.TextField(null=True),
        ),
    ]
