# Generated by Django 3.0 on 2021-09-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_questionofstudent_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionofstudent',
            name='question_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
