# Generated by Django 3.0 on 2021-09-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_questionofstudent_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionofstudent',
            name='correct_answer',
            field=models.TextField(default='-', null=True),
        ),
    ]
